export type ConoceLocale = 'es' | 'en';

export const conoceContent = {
  es: {
    skip: 'Saltar al contenido',
    hero: {
      title: ['Unidos', 'para servir,', 'Fuertes', 'para impactar'],
      cta: 'Descubre cómo SIGUE fortalece organizaciones',
      imageAlt: 'Tres niñas unidas en una comunidad latinoamericana',
    },
    urgency: {
      eyebrow: 'LA URGENCIA QUE NOS MUEVE',
      title: 'Latinoamérica enfrenta',
      accent: 'grandes desafíos.',
      stats: [
        ['19,254', 'feminicidios registrados en los últimos 5 años'],
        ['41', 'millones de niños viven en pobreza extrema en Latinoamérica'],
        ['1.6', 'millones de nacimientos de madres adolescentes al año'],
        ['400.000', 'abortos inducidos en Colombia al año'],
        ['53', 'niños abusados reportados diariamente en Colombia'],
        ['1 de cada 4', 'mujeres han sido víctimas de violencia doméstica'],
      ],
      paragraphs: [
        'Cada día, miles de organizaciones cristianas responden a estos desafíos al servir a personas, familias y comunidades en toda Latinoamérica. Llevan esperanza y promueven el bienestar físico, emocional y espiritual donde más se necesita.',
        'Sin embargo, muchas de estas organizaciones enfrentan obstáculos que limitan su capacidad para crecer, acceder a recursos y multiplicar el impacto de su misión.',
      ],
      cta: 'Descubre las barreras',
    },
    barriers: {
      eyebrow: 'LAS BARRERAS QUE LIMITAN SU IMPACTO',
      title: 'Miles de organizaciones ya están transformando comunidades,',
      accent: 'pero enfrentan barreras para multiplicar su impacto.',
      survival: '1 de cada 3 organizaciones no supera los primeros 5 años de operación.',
      note: 'No por falta de compromiso, sino por la ausencia de capacidades para crecer de manera sostenible y escalar su impacto.',
      items: [
        ['Falta de financiamiento', 'Dificultades para acceder a recursos limitan la sostenibilidad y el crecimiento de sus iniciativas.'],
        ['Escasa evidencia de impacto', 'La dificultad para medir, demostrar y comunicar resultados limita la confianza de donantes y aliados, así como el acceso a nuevas oportunidades.'],
        ['Baja capacidad de gestión', 'La falta de capacidades, procesos y estrategia dificulta el crecimiento sostenible y a escala.'],
        ['Poca visibilidad', 'La baja visibilidad y la ausencia de redes estratégicas reducen las oportunidades de atraer donantes, aliados y nuevas colaboraciones.'],
      ],
      resourcesTitle: 'Además, compiten por recursos muy limitados.',
      resourcesBody: 'Mientras buscan responder a las necesidades de sus comunidades, muchas organizaciones deben hacerlo en un entorno donde solo una pequeña parte de los recursos llega a Latinoamérica y a las organizaciones basadas en la fe.',
      resources: [
        ['1%', 'de las donaciones provenientes de EE. UU. llegan a comunidades latinoamericanas.'],
        ['3%', 'de las donaciones a nivel mundial se destinan a organizaciones basadas en la fe.'],
      ],
      closing: 'Por eso, fortalecer las capacidades de las organizaciones ya no es una opción; es una condición para acceder a recursos, generar confianza y ampliar su impacto.',
      cta: 'Conoce cómo les ayudamos a superar las barreras',
    },
    response: {
      title: 'Nuestra',
      accent: 'respuesta',
      statement: 'Creemos que ninguna organización que está transformando comunidades debería detenerse por falta de las capacidades, las conexiones o los recursos necesarios para multiplicar su impacto.',
      formula: ['potenciar', 'conectar'],
      quote: 'Porque una comunidad verdaderamente transformada impacta generaciones enteras.',
      imageAlt: 'Líderes de SIGUE participando en una jornada de formación',
      benefits: [
        ['Fortalecemos su gestión', 'con herramientas innovadoras y estrategias que les permiten crecer de manera sostenible.'],
        ['Conectamos su misión', 'con una red de expertos, organizaciones, oportunidades de financiamiento y aliados que aceleran su crecimiento.'],
        ['Desarrollamos su capacidad', 'para demostrar su impacto con evidencia y visibilizarlo, para que sean financiables y encontrables por donantes y aliados estratégicos.'],
        ['Acompañamos', 'su desarrollo con mentoría estratégica para fortalecer sus capacidades y prepararlas para escalar su impacto.'],
      ],
      cta: 'Conoce nuestra esencia',
    },
    essence: {
      title: 'Nuestra',
      accent: 'esencia',
      subtitle: 'Las convicciones que guían nuestro trabajo.',
      imageAlt: 'Dos niñas abrazadas en una comunidad',
      items: [
        ['Propósito', 'Existimos para transformar comunidades fortaleciendo a quienes las sirven.', 'Inspiramos, equipamos y conectamos organizaciones y equipos de acción social basados en principios cristianos, reflejando el Reino de Dios mediante procesos de restauración, reconciliación, redención y restitución en las personas, las familias y las comunidades.'],
        ['Visión', 'Comunidades transformadas que impactan generaciones.', 'Soñamos con organizaciones sostenibles, financiables y capaces de generar un impacto físico, emocional y espiritual que trascienda generaciones.'],
        ['Misión', 'Potenciar y conectar organizaciones para multiplicar su impacto.', 'Fortalecemos sus capacidades y las conectamos con conocimiento, recursos y oportunidades para que multipliquen su impacto en las comunidades que sirven.'],
        ['Lo que nos distingue', 'Desarrollamos metodologías prácticas y accionables,', 'basadas en nuestra experiencia fortaleciendo organizaciones y liderando iniciativas de impacto. Cada una está diseñada para facilitar la implementación de cambios reales y sostenibles, adaptados al contexto de cada organización.'],
      ],
      cta: 'Descubre nuestro enfoque',
    },
    theory: {
      eyebrow: 'NUESTRA TEORÍA DE CAMBIO',
      intro: 'Creemos que fortalecer una organización es fortalecer una comunidad. Cuando una organización desarrolla sus capacidades, crece de manera sostenible y multiplica su impacto, más personas, familias y comunidades experimentan una transformación física, emocional y espiritual.',
      challenge: {
        title: 'Desafío',
        lead: 'Organizaciones con alto potencial, pero con capacidades limitadas para crecer.',
        items: ['Acceder a recursos', 'Fortalecer su gestión', 'Ganar visibilidad', 'Demostrar su impacto'],
      },
      solution: {
        title: 'Solución',
        formula: 'potenciar + conectar',
        groups: [
          ['potenciar', ['Acompañamiento', 'Formación', 'Herramientas', 'Aceleración']],
          ['conectar', ['Comunidad', 'Aliados', 'Red de expertos', 'Financiamiento']],
        ],
      },
      transformation: {
        title: 'Transformación',
        groups: [
          ['Organizaciones', ['Más sólidas', 'Más visibles', 'Más financiables', 'Con evidencia de impacto']],
          ['Proyectos', ['Más sólidos', 'Con mayor alcance', 'Con mejores resultados']],
          ['Comunidades', ['Transformación física', 'Transformación emocional', 'Transformación espiritual']],
        ],
      },
    },
    heart: {
      eyebrow: 'EL CORAZÓN DE SIGUE',
      imageAlt: 'Persona en oración al atardecer',
      title: 'Transformamos comunidades',
      accent: 'fortaleciendo a quienes las sirven.',
      intro: 'Creemos que el Reino de Dios se hace visible cuando las personas, las familias y las comunidades experimentan procesos de restauración, reconciliación, redención y restitución en todas las dimensiones de la vida: física, emocional y espiritual.',
      fourRTitle: 'Las 4R de la transformación integral',
      fourR: [
        ['Restaurar', 'Promovemos sanidad y bienestar en las dimensiones física, emocional y espiritual.'],
        ['Reconciliar', 'Acompañamos procesos de reconciliación con Dios, con uno mismo, con los demás y con la creación.'],
        ['Redimir', 'Ayudamos a descubrir y desarrollar el propósito para el cual Dios creó a cada persona y comunidad.'],
        ['Restituir', 'Contribuimos a recuperar la dignidad, las oportunidades y la esperanza para que las personas y comunidades puedan florecer.'],
      ],
      why: '¿POR QUÉ NOS LLAMAMOS SIGUE?',
      whyBody: 'SIGUE es más que un nombre. Es una forma de vivir nuestra misión.',
      values: [
        ['S', 'Servir', 'Seguimos el ejemplo de Jesús, poniendo a las personas en el centro de todo lo que hacemos.'],
        ['I', 'Impactar', 'Hacemos visible el Reino de Dios mediante la transformación de personas, familias y comunidades.'],
        ['G', 'Guiar', 'Inspiramos a líderes y equipos a crecer desde el ser para transformar su manera de servir y multiplicar su misión.'],
        ['U', 'Unir', 'Vivimos como un solo Cuerpo, conectando personas, organizaciones y recursos para cumplir una misión compartida.'],
        ['E', 'Equipar', 'Fortalecemos organizaciones para crecer de manera sostenible y expandir su misión.'],
      ],
      valuesClosing: 'Así vivimos nuestra misión de transformar comunidades fortaleciendo a quienes las sirven.',
      cta: 'Descubre nuestro portafolio',
    },
    portfolio: {
      eyebrow: 'NUESTRO PORTAFOLIO',
      title: 'Así cumplimos',
      accent: 'nuestra misión',
      intro: 'A través de nuestro portafolio de programas, herramientas y acompañamiento, potenciamos y conectamos organizaciones para que crezcan, fortalezcan sus capacidades y multipliquen el impacto que generan en las comunidades que sirven.',
      imageAlt: 'Participantes de SIGUE Network trabajando en equipo',
      cards: [
        ['Acompañamiento', '/images/home-2026/sigue-consulting-transparent.png', 'SIGUE Consulting', '¿Está tu organización lista para dar el siguiente salto de impacto?', 'Acompañamiento estratégico para fortalecer organizaciones, ampliar su impacto y prepararlas para ser financiables, visibles y sostenibles.', 'Conoce más', '/sigue-consulting'],
        ['Formación', '/images/home-2026/sigue-academy-transparent.png', 'SIGUE Academy', '¿Quieres fortalecer las capacidades de tu organización?', 'Programas de formación y certificación que fortalecen las capacidades de líderes y organizaciones para crecer, innovar y generar un impacto sostenible.', 'Conoce más', '/sigue-academy'],
        ['Conexión', '/images/home-2026/sigue-hub-transparent.png', 'SIGUE Hub', '¿Quieres ampliar tu alcance y generar alianzas estratégicas?', 'Una red de recursos, herramientas, líderes y aliados que comparten los mismos valores e impulsan la colaboración, la visibilidad y nuevas oportunidades de impacto.', 'Conéctate', '/sigue-hub'],
        ['Aceleración', '/images/home-2026/sigue-fellows-transparent.png', 'SIGUE Fellows', '¿Está tu organización preparada para multiplicar su impacto?', 'Programa intensivo de 18 semanas para organizaciones de alto potencial, con mentoría personalizada, formación especializada, trabajo aplicado y acceso a capital semilla.', 'Pregúntanos', '/contacto'],
      ],
      assessmentEyebrow: '¿NO SABES POR DÓNDE EMPEZAR?',
      assessmentLead: 'Realiza nuestra autoevaluación',
      assessmentTitle: 'SIGUE Scale-Up Framework™',
      assessmentBody: 'y descubre dónde comenzar a fortalecer tu organización',
      assessmentCta: 'Completa la autoevaluación gratuita',
    },
    history: {
      title: 'Nuestra',
      accent: 'historia',
      intro: 'Toda gran misión comienza con una historia. La nuestra es el resultado de un camino en el que Dios fue formando una visión, preparando el corazón y conectando a quienes ya habían respondido al llamado de servir para expandir Su Reino.',
      items: [
        ['2010', 'Un llamado a servir', 'Mientras servíamos en comunidades alrededor del mundo, Dios puso una visión en el corazón de mi esposo, Steve Callison, un estadounidense que amó profundamente a Colombia, y en el mío. Años después, esa visión daría origen a SIGUE.'],
        ['2013', 'Un sueño que permaneció vivo', 'Tras la partida de Steve, el sueño no desapareció. Mientras continuaba sirviendo en organizaciones internacionales y cuidaba de mi familia, Dios siguió preparándome para el momento en que esa visión cobraría vida.'],
        ['2018', 'Una nueva mirada al servicio', 'Durante un viaje a África con mi hija Anna, la vi cantar para un grupo de niños huérfanos. Al observar cómo se identificaba con ellos desde su propia historia, pues también había perdido a su padre, Dios confirmó mi comprensión del servicio: nuestro servicio a otros comienza cuando somos capaces de ver, escuchar y caminar junto a las personas desde la empatía y el amor.'],
        ['2019', 'El dolor reafirmó mi propósito', 'La pérdida inesperada de mi hijo Juan marcó profundamente mi vida. En medio del duelo, Dios reafirmó que mi vida seguía teniendo propósito y afianzó mi convicción de servir con compasión a quienes sufren, llevando esperanza y acompañándolos a reconciliarse con Dios y a descubrir el propósito que Él tiene para sus vidas.'],
        ['2022', 'La visión comenzó a tomar forma', 'Dios confirmó que había llegado el tiempo de dar forma a la visión que había sembrado años atrás. Comencé a diseñar cómo sería la red, integrando lo aprendido durante más de tres décadas de servicio, desarrollando las metodologías y herramientas que hoy dan vida a SIGUE Network, y convocando a otros con el mismo corazón de servir con excelencia para expandir el Reino de Dios.'],
        ['2024', 'SIGUE Network cobra vida', 'En noviembre de 2024 celebramos la primera Cumbre SIGUE, reuniendo a 56 líderes cristianos que ya habían respondido al llamado a servir. Once años después, la visión que Dios había sembrado se hizo realidad con el nacimiento público de SIGUE Network.'],
        ['Hoy', 'Ahora escribimos esta historia juntos', 'Hoy caminamos junto a líderes y organizaciones cristianas de Hispanoamérica, convencidos de que cuando servimos unidos, somos más fuertes para impactar.'],
      ],
      firstImageAlt: 'Sandra Prieto sirviendo junto a una comunidad en África',
      secondImageAlt: 'Sandra Prieto y su hija junto a niños de una comunidad',
      cta: 'Conoce la historia completa',
    },
    founder: {
      title: 'Conoce a',
      name: 'Sandra Prieto',
      quote: '“Creo que no hay mayor privilegio que servir a otros y verlos florecer en el propósito que Dios les ha confiado”.',
      imageAlt: 'Sandra Prieto durante una conferencia',
      role: 'Fundadora y CEO · SIGUE Network',
      sections: [
        ['Un llamado al servicio', 'Mi camino comenzó a los 23 años, cuando tuve el privilegio de servir como voluntaria acompañando a mujeres en comunidades de Colombia. Lo que inició como un acto de servicio se convirtió en un llamado que Dios ha ido formando durante más de 30 años.'],
        ['Una trayectoria con propósito', 'Ese camino me llevó a servir en 32 países de América Latina, África y Asia, liderando iniciativas de desarrollo e impacto social. A lo largo de este recorrido contribuí a movilizar millones de dólares en inversión social y a fortalecer la gestión de organizaciones que hoy transforman comunidades a gran escala.'],
        ['Lo que guía mi liderazgo', 'Creo que el verdadero impacto nace cuando servimos con humildad, lideramos con excelencia y construimos organizaciones sostenibles.'],
        ['Más sobre mí', 'Además de mi trabajo con SIGUE Network, disfruto servir a través de conferencias, talleres y espacios de formación. Soy esposa, mamá y autora de Me Cambiaron el Libreto, galardonado como Libro del Año en Hispanoamérica 2022. También colaboro en programas radiales, podcasts y otros espacios donde comparto sobre liderazgo, propósito y fe.'],
      ],
      cta: 'Visita sandraprieto.org',
    },
    team: {
      title: 'Nuestro',
      accent: 'equipo',
      subtitle: 'Las personas que hacen posible esta misión, unidas por un mismo propósito',
      boardTitle: 'Junta directiva',
      volunteerTitle: 'Equipo de voluntarios',
      board: [
        ['Sandra Prieto', 'Presidenta', 'sandra-prieto-cutout.webp'],
        ['Mernela Añez', 'Miembro', 'mernela-anez-cutout.webp'],
        ['Mirelida Morales', 'Miembro', 'mirelida-morales-cutout.webp'],
        ['Oscar Lugo', 'Miembro', 'oscar-lugo-cutout-v2.webp'],
      ],
      volunteers: [
        ['Ana M. Peña', 'ana-pena-cutout.webp'],
        ['Belinda Florez', 'belinda-florez-cutout.webp'],
        ['Mitzi Machado', 'mitzi-machado-cutout.webp'],
        ['Jorge H. Mejía', 'jorge-mejia-cutout.webp'],
        ['Alejandro Peralta', 'alejandro-peralta-cutout.webp'],
        ['Mario Blanco', 'mario-blanco-cutout.webp'],
        ['Oscar Lugo', 'oscar-lugo-cutout-v2.webp'],
        ['David Tamayo', 'david-tamayo-cutout-v2.webp'],
      ],
    },
    join: {
      title: 'Súmate a',
      accent: 'la misión',
      subtitle: 'Servir también transforma a quien lo hace. Aporta tu tiempo y talentos a organizaciones que están cambiando comunidades en LATAM.',
      options: [
        ['Voluntariado', 'Remoto · Flexible · Sin costo', 'Creemos que cada talento puede transformar comunidades. Si deseas poner tus habilidades al servicio de organizaciones de impacto, estas son algunas de las áreas donde puedes contribuir. Si no ves la tuya, ¡también queremos conocerte!', ['Gestión de proyectos', 'Finanzas y asuntos legales', 'Comunicación digital', 'Logística y eventos', 'Desarrollo web', 'Coaching y desarrollo personal'], 'Quiero ser voluntario'],
        ['Pasantías', 'Remoto · 3–6 meses · Con certificado', 'Da tus primeros pasos profesionales con propósito. Desarrolla experiencia práctica mientras contribuyes al fortalecimiento de organizaciones que transforman comunidades. Estas son algunas de las áreas donde puedes aprender, aportar y crecer. Si no ves la tuya, ¡también queremos conocerte!', ['Diseño gráfico', 'Gestión de comunidades digitales', 'Marketing digital', 'Producción audiovisual', 'Comunicación institucional', 'Desarrollo web'], 'Postúlate a una pasantía'],
      ],
      processTitle: '¿Cómo es el proceso?',
      processSubtitle: 'Simple, humano y a tu ritmo.',
      process: ['Llenas el formulario de interés', 'Conversamos sobre tu perfil', 'Te orientamos y asignamos', 'Comienzas a servir'],
    },
    resources: {
      title: 'Recursos y',
      accent: 'herramientas',
      subtitle: 'Accede a estrategias y conocimientos para fortalecer tu proyecto e impulsar tu impacto',
      imageAlt: 'Personas revisando informes y estrategias de impacto',
      items: [
        ['Descarga herramientas', 'Encuentra guías prácticas y materiales clave.', 'Acceder', '/herramientas-y-guias'],
        ['Lee el blog', 'Explora artículos con estrategias sobre financiamiento, visibilidad y sostenibilidad organizacional.', 'Leer artículos', '/blog'],
        ['Mira un video', 'Accede a webinars y capacitaciones en YouTube con expertos en impacto social y liderazgo.', 'Ver videos', 'https://www.youtube.com/@SIGUENetwork'],
      ],
    },
    footer: {
      body: 'Potenciamos y conectamos ONGs, proyectos sociales y empresas basados en principios cristianos para transformar integralmente comunidades.',
      discover: 'DESCUBRE',
      participate: 'PARTICIPA',
      rights: '© 2026 SIGUE NETWORK. TODOS LOS DERECHOS RESERVADOS.',
    },
  },
  en: {
    skip: 'Skip to content',
    hero: {
      title: ['United', 'to serve,', 'Stronger', 'to make an impact'],
      cta: 'Discover how SIGUE strengthens organizations',
      imageAlt: 'Three girls together in a Latin American community',
    },
    urgency: {
      eyebrow: 'THE URGENCY THAT MOVES US',
      title: 'Latin America faces',
      accent: 'major challenges.',
      stats: [
        ['19,254', 'femicides recorded in the last 5 years'],
        ['41', 'million children live in extreme poverty in Latin America'],
        ['1.6', 'million births to adolescent mothers each year'],
        ['400,000', 'induced abortions in Colombia each year'],
        ['53', 'cases of child abuse reported daily in Colombia'],
        ['1 in 4', 'women have experienced domestic violence'],
      ],
      paragraphs: [
        'Every day, thousands of Christian organizations respond to these challenges by serving people, families, and communities throughout Latin America. They bring hope and foster physical, emotional, and spiritual well-being where it is needed most.',
        'Yet many of these organizations face obstacles that limit their ability to grow, access resources, and multiply the impact of their mission.',
      ],
      cta: 'Discover the barriers',
    },
    barriers: {
      eyebrow: 'THE BARRIERS LIMITING THEIR IMPACT',
      title: 'Thousands of organizations are already transforming communities,',
      accent: 'but they face barriers to multiplying their impact.',
      survival: '1 in 3 organizations does not make it beyond its first 5 years of operation.',
      note: 'Not for lack of commitment, but because they lack the capabilities needed to grow sustainably and scale their impact.',
      items: [
        ['Limited funding', 'Difficulty accessing resources limits the sustainability and growth of their initiatives.'],
        ['Limited impact evidence', 'Difficulty measuring, demonstrating, and communicating results limits donor and partner trust, as well as access to new opportunities.'],
        ['Limited management capacity', 'A lack of capabilities, processes, and strategy makes sustainable growth and scale difficult.'],
        ['Limited visibility', 'Limited visibility and a lack of strategic networks reduce opportunities to attract donors, partners, and new collaborations.'],
      ],
      resourcesTitle: 'They also compete for very limited resources.',
      resourcesBody: 'As they respond to their communities’ needs, many organizations operate in an environment where only a small portion of resources reaches Latin America and faith-based organizations.',
      resources: [
        ['1%', 'of U.S. donations reach Latin American communities.'],
        ['3%', 'of global donations go to faith-based organizations.'],
      ],
      closing: 'Strengthening organizational capacity is no longer optional; it is essential for accessing resources, building trust, and expanding impact.',
      cta: 'See how we help them overcome these barriers',
    },
    response: {
      title: 'Our',
      accent: 'response',
      statement: 'We believe no organization transforming communities should have to stop because it lacks the capabilities, connections, or resources needed to multiply its impact.',
      formula: ['strengthen', 'connect'],
      quote: 'Because a truly transformed community impacts entire generations.',
      imageAlt: 'SIGUE leaders taking part in a training session',
      benefits: [
        ['We strengthen their management', 'with innovative tools and strategies that enable sustainable growth.'],
        ['We connect their mission', 'with a network of experts, organizations, funding opportunities, and allies who accelerate their growth.'],
        ['We build their capacity', 'to demonstrate impact with evidence and gain visibility, making them fundable and discoverable by donors and strategic allies.'],
        ['We walk alongside them', 'with strategic mentoring to strengthen their capabilities and prepare them to scale their impact.'],
      ],
      cta: 'Discover our essence',
    },
    essence: {
      title: 'Our',
      accent: 'essence',
      subtitle: 'The convictions that guide our work.',
      imageAlt: 'Two girls embracing in a community',
      items: [
        ['Purpose', 'We exist to transform communities by strengthening those who serve them.', 'We inspire, equip, and connect Christian social-action organizations and teams, reflecting God’s Kingdom through restoration, reconciliation, redemption, and restitution in people, families, and communities.'],
        ['Vision', 'Transformed communities that impact generations.', 'We envision sustainable, fundable organizations capable of creating physical, emotional, and spiritual impact that transcends generations.'],
        ['Mission', 'Strengthen and connect organizations to multiply their impact.', 'We build their capabilities and connect them with knowledge, resources, and opportunities so they can multiply their impact in the communities they serve.'],
        ['What sets us apart', 'We develop practical, actionable methodologies,', 'grounded in our experience strengthening organizations and leading impact initiatives. Each is designed to enable real, sustainable change adapted to every organization’s context.'],
      ],
      cta: 'Discover our approach',
    },
    theory: {
      eyebrow: 'OUR THEORY OF CHANGE',
      intro: 'We believe strengthening an organization means strengthening a community. When an organization builds its capabilities, grows sustainably, and multiplies its impact, more people, families, and communities experience physical, emotional, and spiritual transformation.',
      challenge: {
        title: 'Challenge',
        lead: 'High-potential organizations with limited capacity to grow.',
        items: ['Access resources', 'Strengthen management', 'Gain visibility', 'Demonstrate impact'],
      },
      solution: {
        title: 'Solution',
        formula: 'strengthen + connect',
        groups: [
          ['strengthen', ['Guidance', 'Training', 'Tools', 'Acceleration']],
          ['connect', ['Community', 'Allies', 'Expert network', 'Funding']],
        ],
      },
      transformation: {
        title: 'Transformation',
        groups: [
          ['Organizations', ['Stronger', 'More visible', 'More fundable', 'Evidence-backed impact']],
          ['Projects', ['Stronger', 'Greater reach', 'Better outcomes']],
          ['Communities', ['Physical transformation', 'Emotional transformation', 'Spiritual transformation']],
        ],
      },
    },
    heart: {
      eyebrow: 'THE HEART OF SIGUE',
      imageAlt: 'A person praying at sunset',
      title: 'We transform communities',
      accent: 'by strengthening those who serve them.',
      intro: 'We believe God’s Kingdom becomes visible when people, families, and communities experience restoration, reconciliation, redemption, and restitution in every dimension of life: physical, emotional, and spiritual.',
      fourRTitle: 'The 4Rs of holistic transformation',
      fourR: [
        ['Restore', 'We foster healing and well-being in the physical, emotional, and spiritual dimensions.'],
        ['Reconcile', 'We accompany reconciliation with God, oneself, others, and creation.'],
        ['Redeem', 'We help people discover and develop the purpose for which God created each person and community.'],
        ['Reinstate', 'We help restore dignity, opportunity, and hope so people and communities can flourish.'],
      ],
      why: 'WHY ARE WE CALLED SIGUE?',
      whyBody: 'SIGUE is more than a name. It is a way of living our mission.',
      values: [
        ['S', 'Serve', 'We follow Jesus’ example, placing people at the center of everything we do.'],
        ['I', 'Impact', 'We make God’s Kingdom visible through the transformation of people, families, and communities.'],
        ['G', 'Guide', 'We inspire leaders and teams to grow from within, transform how they serve, and multiply their mission.'],
        ['U', 'Unite', 'We live as one Body, connecting people, organizations, and resources around a shared mission.'],
        ['E', 'Equip', 'We strengthen organizations to grow sustainably and expand their mission.'],
      ],
      valuesClosing: 'This is how we live our mission of transforming communities by strengthening those who serve them.',
      cta: 'Discover our portfolio',
    },
    portfolio: {
      eyebrow: 'OUR PORTFOLIO',
      title: 'How we fulfill',
      accent: 'our mission',
      intro: 'Through our portfolio of programs, tools, and guidance, we strengthen and connect organizations so they can grow, build their capabilities, and multiply their impact in the communities they serve.',
      imageAlt: 'SIGUE Network participants working together',
      cards: [
        ['Guidance', '/images/home-2026/sigue-consulting-transparent.png', 'SIGUE Consulting', 'Is your organization ready for its next impact leap?', 'Strategic guidance to strengthen organizations, expand their impact, and prepare them to become fundable, visible, and sustainable.', 'Learn more', '/sigue-consulting'],
        ['Training', '/images/home-2026/sigue-academy-transparent.png', 'SIGUE Academy', 'Do you want to strengthen your organization’s capabilities?', 'Training and certification programs that equip leaders and organizations to grow, innovate, and create sustainable impact.', 'Learn more', '/sigue-academy'],
        ['Connection', '/images/home-2026/sigue-hub-transparent.png', 'SIGUE Hub', 'Do you want to expand your reach and build strategic alliances?', 'A network of resources, tools, leaders, and allies who share common values and advance collaboration, visibility, and new impact opportunities.', 'Connect', '/sigue-hub'],
        ['Acceleration', '/images/home-2026/sigue-fellows-transparent.png', 'SIGUE Fellows', 'Is your organization prepared to multiply its impact?', 'An intensive 18-week program for high-potential organizations, with personalized mentoring, specialized training, applied work, and access to seed capital.', 'Ask us', '/contacto'],
      ],
      assessmentEyebrow: 'NOT SURE WHERE TO BEGIN?',
      assessmentLead: 'Take our self-assessment',
      assessmentTitle: 'SIGUE Scale-Up Framework™',
      assessmentBody: 'and discover where to begin strengthening your organization',
      assessmentCta: 'Complete the free self-assessment',
    },
    history: {
      title: 'Our',
      accent: 'story',
      intro: 'Every great mission begins with a story. Ours is the result of a journey in which God shaped a vision, prepared hearts, and connected those who had already answered the call to serve and expand His Kingdom.',
      items: [
        ['2010', 'A call to serve', 'As we served communities around the world, God placed a vision in the heart of my husband, Steve Callison—an American who loved Colombia deeply—and in mine. Years later, that vision would give rise to SIGUE.'],
        ['2013', 'A dream that remained alive', 'After Steve’s passing, the dream did not disappear. As I continued serving with international organizations and caring for my family, God continued preparing me for the moment when that vision would come to life.'],
        ['2018', 'A new perspective on service', 'During a trip to Africa with my daughter Anna, I watched her sing for a group of orphaned children. Seeing how she connected with them through her own story confirmed my understanding of service: serving others begins when we see, listen, and walk alongside people with empathy and love.'],
        ['2019', 'Pain reaffirmed my purpose', 'The unexpected loss of my son Juan marked my life deeply. In the midst of grief, God reaffirmed that my life still had purpose and strengthened my conviction to serve those who suffer with compassion, hope, and accompaniment.'],
        ['2022', 'The vision began to take shape', 'God confirmed that the time had come to shape the vision planted years before. I began designing the network, integrating more than three decades of service and developing the methodologies and tools that now bring SIGUE Network to life.'],
        ['2024', 'SIGUE Network comes to life', 'In November 2024 we held the first SIGUE Summit, bringing together 56 Christian leaders who had answered the call to serve. Eleven years later, the vision God had planted became a public reality with the birth of SIGUE Network.'],
        ['Today', 'Now we write this story together', 'Today we walk alongside Christian leaders and organizations across Hispanic America, convinced that when we serve united, we are stronger to make an impact.'],
      ],
      firstImageAlt: 'Sandra Prieto serving alongside a community in Africa',
      secondImageAlt: 'Sandra Prieto and her daughter with children from a community',
      cta: 'Discover the full story',
    },
    founder: {
      title: 'Meet',
      name: 'Sandra Prieto',
      quote: '“I believe there is no greater privilege than serving others and seeing them flourish in the purpose God has entrusted to them.”',
      imageAlt: 'Sandra Prieto speaking at a conference',
      role: 'Founder and CEO · SIGUE Network',
      sections: [
        ['A call to serve', 'My journey began at age 23, when I had the privilege of volunteering alongside women in Colombian communities. What began as an act of service became a calling God has shaped for more than 30 years.'],
        ['A purpose-driven journey', 'That journey took me to serve in 32 countries across Latin America, Africa, and Asia, leading development and social-impact initiatives. Along the way I helped mobilize millions of dollars in social investment and strengthen organizations that now transform communities at scale.'],
        ['What guides my leadership', 'I believe true impact is born when we serve with humility, lead with excellence, and build sustainable organizations.'],
        ['More about me', 'In addition to my work with SIGUE Network, I enjoy serving through conferences, workshops, and training spaces. I am a wife, mother, and author of Me Cambiaron el Libreto, named Book of the Year in Hispanic America in 2022. I also contribute to radio programs, podcasts, and other spaces where I speak about leadership, purpose, and faith.'],
      ],
      cta: 'Visit sandraprieto.org',
    },
    team: {
      title: 'Our',
      accent: 'team',
      subtitle: 'The people who make this mission possible, united by one purpose',
      boardTitle: 'Board of directors',
      volunteerTitle: 'Volunteer team',
      board: [
        ['Sandra Prieto', 'President', 'sandra-prieto-cutout.webp'],
        ['Mernela Añez', 'Member', 'mernela-anez-cutout.webp'],
        ['Mirelida Morales', 'Member', 'mirelida-morales-cutout.webp'],
        ['Oscar Lugo', 'Member', 'oscar-lugo-cutout-v2.webp'],
      ],
      volunteers: [
        ['Ana M. Peña', 'ana-pena-cutout.webp'], ['Belinda Florez', 'belinda-florez-cutout.webp'],
        ['Mitzi Machado', 'mitzi-machado-cutout.webp'], ['Jorge H. Mejía', 'jorge-mejia-cutout.webp'],
        ['Alejandro Peralta', 'alejandro-peralta-cutout.webp'], ['Mario Blanco', 'mario-blanco-cutout.webp'],
        ['Oscar Lugo', 'oscar-lugo-cutout-v2.webp'], ['David Tamayo', 'david-tamayo-cutout-v2.webp'],
      ],
    },
    join: {
      title: 'Join',
      accent: 'the mission',
      subtitle: 'Serving also transforms the person who serves. Contribute your time and talents to organizations changing communities across Latin America.',
      options: [
        ['Volunteer', 'Remote · Flexible · Free', 'We believe every talent can transform communities. Put your skills at the service of impact organizations in one of these areas. If you do not see yours, we still want to meet you!', ['Project management', 'Finance and legal affairs', 'Digital communication', 'Logistics and events', 'Web development', 'Coaching and personal development'], 'I want to volunteer'],
        ['Internships', 'Remote · 3–6 months · Certificate included', 'Take your first purpose-driven professional steps. Gain practical experience while strengthening organizations that transform communities. Learn, contribute, and grow in one of these areas.', ['Graphic design', 'Digital community management', 'Digital marketing', 'Audiovisual production', 'Institutional communication', 'Web development'], 'Apply for an internship'],
      ],
      processTitle: 'What is the process?',
      processSubtitle: 'Simple, human, and at your pace.',
      process: ['Complete the interest form', 'We discuss your profile', 'We guide and match you', 'You begin serving'],
    },
    resources: {
      title: 'Resources and',
      accent: 'tools',
      subtitle: 'Access strategies and knowledge to strengthen your project and advance your impact',
      imageAlt: 'People reviewing impact reports and strategies',
      items: [
        ['Download tools', 'Find practical guides and essential materials.', 'Access', '/herramientas-y-guias'],
        ['Read the blog', 'Explore strategies for funding, visibility, and organizational sustainability.', 'Read articles', '/blog'],
        ['Watch a video', 'Access YouTube webinars and training with experts in social impact and leadership.', 'Watch videos', 'https://www.youtube.com/@SIGUENetwork'],
      ],
    },
    footer: {
      body: 'We strengthen and connect NGOs, social projects, and businesses grounded in Christian principles to transform communities holistically.',
      discover: 'DISCOVER',
      participate: 'PARTICIPATE',
      rights: '© 2026 SIGUE NETWORK. ALL RIGHTS RESERVED.',
    },
  },
} as const;
